import { Home, User, Layers3, GlobeLock } from "lucide-react";
import slug from "slug";
import {
  SiNextdotjs,
  SiTypescript,
  SiReact,
  SiPwa,
  SiOpensourceinitiative,
} from "react-icons/si";

// SideBar Route Links
export const sidebarRouteLinks = [
  {
    name: "Home",
    href: "/",
    key: "home",
    icon: Home,
    current: false,
  },
  {
    name: "Projects",
    href: "/projects",
    key: "projects",
    icon: GlobeLock,
    current: false,
  },
  {
    name: "About",
    href: "/about",
    key: "about",
    icon: User,
    current: false,
  },
  {
    name: "Stack",
    href: "/stack",
    key: "stack",
    icon: Layers3,
    current: false,
  },
];

// Project Data  Links
export const projectLinks = [
  {
    imageUrl: "/project-7.png",
    videoUrl: "https://youtu.be/o9fTjNIPjpU?si=A1R10OW3E-nWadN3",
    imageUrls: ["/project-7.png", "/project-7.png"],
    projectTitle: "AI Powered Incite360",
    subTitle:
      "🚀  AI Powered Incite360 Application is a powerful, customizable survey platform designed to help businesses collect, analyze, and act on customer feedback. The platform enables organizations to create surveys, distribute them across multiple channels, analyze responses in real-time, and integrate with external platforms like Google and Facebook for comprehensive review management.",
    stack: [
      "AI Integration",
      "TypeScript",
      "NextJS",
      "React-Redux",
      "AWS Amplify",
      "Tailwind",
      "Shadcn/UI",
      "NestJs Backend",
      "Prisma",
    ],
    repositoryUrl: "https://github.com/geodevcodes",
    projectUrl: "https://app.theincite360.com/en",
    category: ["TypeScript", "NextJs", "React-Redux", "AI", "Web App", "PWA"],
    projectFeatures: [
      "🌐 Next.js App Router",
      "🔐 NextAuth Authentication",
      "💨 Payment Service with Paystack",
      "🎨 Styling with tailwindcss",
      "✅ React TanStack Query",
      "💵 React-TanStack Table",
      "🐐 React-Redux",
      "✅ Github Pull Request Template",
      "💵 Github Workflow",
      "😶‍🌫️ Deployment to AWS Amplify & Vercel",
      "💽 OutStanding ReadMe",
    ],
  },
  {
    imageUrl: "/monae.png",
    videoUrl: "",
    imageUrls: ["/monae2.png", "/monae3.png"],
    projectTitle: "Monae",
    subTitle:
      "🚀  Monae is an AI-powered personal finance assistant built for African youth, starting with Nigeria. It securely integrates with local banks to provide real-time spend tracking, smart insights, and motivational, emotional-aware nudges. This conversational tool helps users effortlessly manage budgets and build healthier money habits.",
    stack: [
      "TypeScript",
      "ReactNative",
      "Expo",
      "Google Maps",
      "Expo EAS",
      "Tailwindcss",
    ],
    repositoryUrl: "https://github.com/geodevcodes/monae",
    projectUrl: "https://monae-demo.vercel.app/",
    category: ["TypeScript", "ReactNative", "Expo", "ReactJs", "ReactNative"],
    projectFeatures: [
      "🌐 React Native (Expo)",
      "🔐 NestJs Backend",
      "🎨 Styling with tailwindcss",
      "✅ React TanStack Query",
      "🐐 React-Context API",
      "✅ Github Pull Request Template",
      "💵 Github Workflow",
      "😶‍🌫️ Deployment to Expo EAS",
      "💽 OutStanding ReadMe",
    ],
  },
  {
    imageUrl: "/geomatic-connect.png",
    videoUrl:
      "https://res.cloudinary.com/dgfjxhoae/video/upload/v1753978858/geomatic-connect/Are_you_a_geomatic_student__3_t4pko8.mp4",
    imageUrls: ["/geomatic-connect.webp", "/geomatic-connect.png"],
    projectTitle: "Geomatic Connect",
    subTitle:
      "🚀 A modern SaaS Job portal connecting Geomatics students with companies for internships and training programs. Developed with Next.js 14, TailwindCSS, MongoDB, and NextAuth with OAuth (Google, GitHub), featuring Paystack payment integration, unit testing, and deployment on aws amplify. (https://www.geomaticconnect.work/)",
    stack: [
      "TypeScript",
      "NextJS",
      "NextAuth",
      "React-Query",
      "Vercel",
      "Tailwind",
      "ExpressJs",
      "MongoDB",
      "PayStack",
      "Unit Testing",
    ],
    repositoryUrl: "https://github.com/geodevcodes",
    projectUrl: "https://www.geomaticconnect.work/",
    category: ["TypeScript", "NextJs", "AI", "Web App", "PWA"],
    projectFeatures: [
      "🌐 Next.js App Router",
      "🔐 NextAuth Authentication",
      "📧 Email/Password Auth",
      "🔑 OAuth (Google and GitHub)",
      "💽 MongoDB Database",
      "💨 Payment Service with PayStack",
      "🎨 Styling with tailwindcss",
      "✅ Github Pull Request Template",
      "💵 Github Workflow",
      "🐐 Unit Testing",
      "😶‍🌫️ Deployment to Vercel",
      "💽 OutStanding ReadMe",
    ],
  },
  {
    imageUrl: "/alivehome.png",
    videoUrl: "",
    imageUrls: ["/alivehome3.png", "/alivehome2.png"],
    projectTitle: "Alive Home",
    subTitle:
      "🚀 Alive Home uses proprietary AI to verify every listing, predict the fair market value, and intelligently match users with their ideal properties. Our algorithm learns your precise preferences to eliminate noise and ensure you only see listings that have been physically verified by our team. This creates a transparent, stress-free home discovery experience with no agents required.",
    stack: [
      "TypeScript",
      "NextJS",
      "Kinde",
      "Sanity",
      "Vercel",
      "Tailwind",
      "Shadcn/UI",
      "Supabase",
    ],
    repositoryUrl: "https://github.com/geodevcodes/",
    projectUrl: "https://www.alivehome.co/",
    category: ["TypeScript", "NextJs", "Web App", "ReactJs"],
    projectFeatures: [
      "🌐 Next.js App Router",
      "📧 Passwordless Auth",
      "🔑 OAuth (Google and GitHub)",
      "💽 SQL Database",
      "🎨 Styling with tailwindcss and shadcn UI",
      "✅ Github Pull Request Template",
      "💵 Github Workflow",
      "💵 Store Projects in alivehome github repo",
      "💽 OutStanding ReadMe",
      "😶‍🌫️ Deployment to Shipspace",
    ],
  },
  {
    imageUrl: "/airide.png",
    videoUrl: "",
    imageUrls: ["/airide.png", "/airide.png"],
    projectTitle: "AIRIDE Mobile APP",
    subTitle:
      "🚀  Built with React Native for handling the user interface, Google Maps for rendering maps with directions, paystack for handling payments, and styled with TailwindCSS, AI Ride is a perfect mobile app",
    stack: [
      "TypeScript",
      "ReactNative",
      "Expo",
      "AI",
      "Google Maps",
      "Zustand",
      "AWS Amplify",
      "Tailwindcss",
    ],
    repositoryUrl: "https://github.com/geodevcodes/rn-aiRide",
    projectUrl: "https://expo.dev/artifacts/eas/vxr5E8gf1q25nq9HqYBF6u.apk",
    category: ["TypeScript", "ReactNative", "Expo", "ReactJs", "ReactNative"],
    projectFeatures: [
      "🌐 React Native (Expo)",
      "🔐 NestJs Backend",
      "🎨 Styling with tailwindcss",
      "✅ React TanStack Query",
      "🐐 React-Redux",
      "✅ Github Pull Request Template",
      "💵 Github Workflow",
      "😶‍🌫️ Deployment to Expo EAS",
      "💽 OutStanding ReadMe",
    ],
  },
  {
    imageUrl: "/clear-essence1.png",
    videoUrl: "",
    imageUrls: ["/clear-essence2.png", "/clear-essence3.png"],
    projectTitle: "Virtual Menu",
    subTitle:
      "🚀 This application transforms Clear Essence Hotel & Spa’s guest experience by replacing traditional menus with a seamless QR-code digital menu system accessible on any mobile device. The platform ensures guests can explore restaurant and spa offerings with ease. Its scalable architecture also positions the hotel for future expansion into advanced features like real-time analytics, digital ordering, and integrated service bookings.",
    stack: [
      "TypeScript",
      "NextJS",
      "NestJs Backend",
      "Vercel",
      "TailwindCSS",
      "Prisma",
    ],
    repositoryUrl: "https://github.com/geodevcodes",
    projectUrl: "https://staging.menu.tezzasolutions.com/",
    category: ["TypeScript", "NextJs", "Web Application"],
    projectFeatures: [
      "🌐 Next.js App Router",
      "🎨 Styling with Tailwindcss",
      "✅ Github Pull Request Template",
      "💵 Github Workflow",
      "💵 Store Projects in Sanity",
      "🐐 Bento Layout",
      "💽 OutStanding ReadMe",
      "😶‍🌫️ Deployment to Godaddy",
    ],
  },
  {
    imageUrl: "/afrenai.png",
    videoUrl: "",
    imageUrls: ["/afrenai2.png", "/afrenai2.png"],
    projectTitle: "Afren AI operating system",
    subTitle:
      "🚀  AI-driven operating system that transforms project ideas into shipped products by automating project scoping, team matching, and execution.",
    stack: [
      "TypeScript",
      "NextJS",
      "NextAuth",
      "React-Query",
      "gemini ai model",
      "Tailwindcss",
      "Prisma",
      "MongoDB",
      "Elevenlab AI",
      "Unit Testing",
    ],
    repositoryUrl: "https://github.com/geodevcodes",
    projectUrl: "https://afren-ai-frontend.vercel.app/",
    category: ["TypeScript", "NextJs", "AI", "Web App"],
    projectFeatures: [
      "🌐 Next.js App Router",
      "🔐 NextAuth Authentication",
      "📧 Email/Password Auth",
      "💽 MongoDB Database",
      "🔐 Prisma ORM",
      "🎨 Styling with tailwindcss",
      "✅ Github Pull Request Template",
      "💵 Github Workflow",
      "🐐 Unit Testing",
      "😶‍🌫️ Deployment to Vercel",
      "💽 OutStanding ReadMe",
    ],
  },
  {
    imageUrl: "/gtworld-clone.png",
    videoUrl:
      "https://res.cloudinary.com/dgfjxhoae/video/upload/v1764596864/geodevcodes-portfolio/Rasheed_Olatunde_s_Video_-_Dec_1_2025-VEED_knca6f.mp4",
    imageUrls: ["/gtworld-clone2.png", "/gtworld-clone3.png"],
    projectTitle: "GTWorld-Clone",
    subTitle:
      "🚀 With GTWorld-Clone, you can transfer funds, pay bills, manage cards, and monitor your account activity – all from the palm of your hand. GTWorld-Clone is a demonstration of how a digital banking platform can offer fast, secure, and user-friendly services. It’s designed for customers who want full control over their money management and a seamless banking experience on the go.",
    stack: [
      "TypeScript",
      "React-Native",
      "Expo",
      "React-Query",
      "NextJS",
      "Nativewind",
      "React-native Reanimated",
      "Firebase",
      "PayStack",
      "Unit Testing",
    ],
    repositoryUrl: "https://github.com/geodevcodes/gt-clone",
    projectUrl: "https://gtclone-demo.vercel.app/",
    category: ["TypeScript", "NextJs", "Web App", "PWA", "ReactJs"],
    projectFeatures: [
      "🌐 React-Native (Expo)",
      "🔐 React-Native Reanimated",
      "🎨 Styling with Nativewind",
      "📧 Passwordless Auth",
      "🔑 OAuth (Google and GitHub)",
      "💨 Payment Service with PayStack",
      "✅ Github Pull Request Template",
      "💵 Github Workflow",
      "🐐 Unit Testing",
      "😶‍🌫️ Deployment to expo eas",
      "💽 OutStanding ReadMe",
    ],
  },
  {
    imageUrl: "/portfolio.png",
    videoUrl:
      "https://res.cloudinary.com/dgfjxhoae/video/upload/v1764686146/geodevcodes-portfolio/Screen_Recording_2025-12-02_at_15.32.36_zv0gvq.mov",
    imageUrls: ["/portfolio.png", "/portfolio.png"],
    projectTitle: "My Portfolio Website",
    subTitle:
      "🚀   AI-Augmented Portfolio: Blogify for content, ElevenLabs for conversation. Global-ready with robust internationalization and adaptive dark/light modes.",
    stack: [
      "TypeScript",
      "NextJS",
      "NextAuth",
      "Vercel",
      "Tailwind",
      "Shadcn/UI",
      "MongoDB",
    ],
    repositoryUrl: "https://github.com/geodevcodes/v2_portfolio",
    projectUrl: "https://geodevcodes.vercel.app/",
    category: ["TypeScript", "NextJs", "React-Redux", "AI", "Web App", "PWA"],
    projectFeatures: [
      "🌐 Next.js App Router",
      "🔐 Kinde Authentication",
      "📧 Passwordless Auth",
      "🔑 OAuth (Google and GitHub)",
      "🎨 Styling with tailwindcss and shadcn UI",
      "✅ Github Pull Request Template",
      "💵 Github Workflow",
      "💵 Store Projects in Sanity",
      "🐐 Bento Layout",
      "💽 OutStanding ReadMe",
      "😶‍🌫️ Deployment to Vercel",
    ],
  },
  {
    imageUrl: "/scoutbeta.png",
    videoUrl: "",
    imageUrls: ["/scoutbeta2.png", "/scoutbeta3.png"],
    projectTitle: "ScoutBeta: Marketplace for Space and Location Scouting",
    subTitle:
      "🚀 No.1 Online marketplace for space and location scouting for creators just in 3 clicks.",
    stack: [
      "TypeScript",
      "NextJS",
      "NextAuth",
      "Vercel",
      "Tailwind",
      "Shadcn/UI",
      "Zustand",
    ],
    repositoryUrl: "https://github.com/scoutbeta-solutions",
    projectUrl: "https://www.scoutbeta.com/",
    category: ["TypeScript", "NextJs", "Zustand", "Web App", "PWA"],
    projectFeatures: [
      "🌐 Next.js App Router",
      "🔐 NextAuth Authentication",
      "🔑 OAuth (Google and GitHub)",
      "💽 Supabase Database",
      "🎨 Styling with tailwindcss and shadcn UI",
      "✅ Github Pull Request Template",
      "💵 Github Workflow",
      "🐐 Bento Layout",
      "💽 OutStanding ReadMe",
      "😶‍🌫️ Deployment to AWS Amplify",
    ],
  },
  {
    imageUrl: "/aora.webp",
    videoUrl: "",
    imageUrls: ["/aora.webp", "/aora.webp"],
    projectTitle: "Aora Mobile APP",
    subTitle:
      "🚀  Built with React Native for seamless user experiences, Animatable for captivating animations, and integrated with the dependable backend systems of Appwrite, this app showcases impressive design and functionality, enabling seamless sharing of AI videos within the community.",
    stack: [
      "AI Integration",
      "TypeScript",
      "NextJS",
      "React-Redux",
      "AWS Amplify",
      "Tailwindcss",
      "Shadcn/UI",
      "Appwrite",
    ],
    repositoryUrl: "https://github.com/geodevcodes/rn-aora",
    projectUrl: "https://expo.dev/artifacts/eas/qUhLQYymPhGmxce2LLbz5c.apk",
    category: [
      "TypeScript",
      "ReactNative",
      "Expo",
      "AI",
      "ReactJs",
      "ReactNative",
    ],
    projectFeatures: [
      "🌐 React Native (Expo)",
      "🔐 Appwrite",
      "🎨 Styling with tailwindcss",
      "✅ React TanStack Query",
      "💵 React-TanStack Table",
      "🐐 React-Redux",
      "✅ Github Pull Request Template",
      "💵 Github Workflow",
      "😶‍🌫️ Deployment to Expo EAS",
      "💽 OutStanding ReadMe",
    ],
  },
  {
    imageUrl: "/must.webp",
    videoUrl: "",
    imageUrls: ["/must.webp", "/must.webp"],
    projectTitle: "Must Culture Share: Internationalization with i18n",
    subTitle:
      "🚀 A multilingual must-culture website supporting five languages (English, Korean, Chinese, German, Arabic) built with Next.js, next-i18n, TailwindCSS, and Shadcn UI, with Sanity CMS for content management, deployed on Vercel",
    stack: [
      "TypeScript",
      "NextJS",
      "Kinde",
      "Sanity",
      "Vercel",
      "Tailwind",
      "Shadcn/UI",
      "Prisma",
    ],
    repositoryUrl: "https://github.com/geodevcodes/must",
    projectUrl: "https://must-geodevcodes.vercel.app/ko",
    category: ["TypeScript", "NextJs", "Web Application"],
    projectFeatures: [
      "🌐 Next.js App Router",
      "🎨 Styling with tailwindcss and shadcn UI",
      "✅ Github Pull Request Template",
      "💵 Github Workflow",
      "💵 Store Projects in Sanity",
      "🐐 Bento Layout",
      "💽 OutStanding ReadMe",
      "😶‍🌫️ Deployment to Vercel",
    ],
  },
].map((project) => ({
  ...project,
  slug: slug(project.projectTitle, { lower: true }),
}));

// Project Category Options
export const categoryOptions = [
  {
    label: "AI",
    value: "AI",
    icon: SiOpensourceinitiative,
  },
  {
    label: "NextJs",
    value: "NextJs",
    icon: SiNextdotjs,
  },
  {
    label: "PWA",
    value: "PWA",
    icon: SiPwa,
  },
  {
    label: "TypeScript",
    value: "TypeScript",
    icon: SiTypescript,
  },
  {
    label: "ReactJs",
    value: "ReactJs",
    icon: SiReact,
  },
];
