import { Home, User, Layers3, GlobeLock } from "lucide-react";
import {
  SiNextdotjs,
  SiTypescript,
  SiReact,
  SiPwa,
  SiOpensourceinitiative,
} from "react-icons/si";

// SideBar Route Links
export const sidebarRouteLinks = [
  {
    name: "Home",
    href: "/",
    key: "home",
    icon: Home,
    current: false,
  },
  {
    name: "Projects",
    href: "/projects",
    key: "projects",
    icon: GlobeLock,
    current: false,
  },
  {
    name: "About",
    href: "/about",
    key: "about",
    icon: User,
    current: false,
  },
  {
    name: "Stack",
    href: "/stack",
    key: "stack",
    icon: Layers3,
    current: false,
  },
];

// Project Data  Links
export const projectLinks = [
  {
    id: "1",
    imageUrl: "/project-7.png",
    projectTitle: "AI Powered Survey Engine",
    subTitle:
      "🚀  Outstanding AI Powered Survey Engine Application, In this app you can create and customize your Surveys or build your survey with AI automation and send to your Customer/Client with Survey Engine app? Build with popular tools like NextJs, React-Redux, NodeJs for managing our database, Next-Auth for authentication, React-TanStack Query for efficient data Fetching, and spicing things up with Tailwind.css for some awesome styling.",
    stack: [
      "AI Integration",
      "TypeScript",
      "NextJS",
      "React-Redux",
      "AWS Amplify",
      "Tailwind",
      "Shadcn/UI",
      "NestJs Backend",
      "Prisma",
    ],
    repositoryUrl: "https://github.com/olatunde1998/survey-engine",
    projectUrl: "https://app.thesurveyengine.com/en",
    category: ["TypeScript", "NextJs", "React-Redux", "AI", "Web App", "PWA"],
    projectFeatures: [
      "🌐 Next.js App Router",
      "🔐 NextAuth Authentication",
      "💨 Payment Service with Flutterwave",
      "🎨 Styling with tailwindcss",
      "✅ React TanStack Query",
      "💵 React-TanStack Table",
      "🐐 React-Redux",
      "✅ Github Pull Request Template",
      "💵 Github Workflow",
      "😶‍🌫️ Deployment to AWS Amplify & Vercel",
      "💽 OutStanding ReadMe",
    ],
  },
  {
    id: "2",
    imageUrl: "/aora.webp",
    projectTitle: "Aora Mobile APP",
    subTitle:
      "🚀  Built with React Native for seamless user experiences, Animatable for captivating animations, and integrated with the dependable backend systems of Appwrite, this app showcases impressive design and functionality, enabling seamless sharing of AI videos within the community.",
    stack: [
      "AI Integration",
      "TypeScript",
      "NextJS",
      "React-Redux",
      "AWS Amplify",
      "Tailwindcss",
      "Shadcn/UI",
      "Appwrite",
    ],
    repositoryUrl: "https://github.com/olatunde1998/rn-aora",
    projectUrl: "https://expo.dev/artifacts/eas/qUhLQYymPhGmxce2LLbz5c.apk",
    category: [
      "TypeScript",
      "ReactNative",
      "Expo",
      "AI",
      "ReactJs",
      "ReactNative",
    ],
    projectFeatures: [
      "🌐 React Native (Expo)",
      "🔐 Appwrite",
      "🎨 Styling with tailwindcss",
      "✅ React TanStack Query",
      "💵 React-TanStack Table",
      "🐐 React-Redux",
      "✅ Github Pull Request Template",
      "💵 Github Workflow",
      "😶‍🌫️ Deployment to Expo EAS",
      "💽 OutStanding ReadMe",
    ],
  },
  {
    id: "3",
    imageUrl: "/geomatic-connect.webp",
    projectTitle: "Geomatics Connect | Job Board Platform",
    subTitle:
      "🚀 A modern SaaS Job portal connecting Geomatics students with companies for internships and training programs. Developed with Next.js 14, TailwindCSS, MongoDB, and NextAuth with OAuth (Google, GitHub), featuring Paystack payment integration, unit testing, and deployment on aws amplify. (https://www.geomaticconnect.work/)",
    stack: [
      "TypeScript",
      "NextJS",
      "NextAuth",
      "React-Query",
      "Vercel",
      "Tailwind",
      "ExpressJs",
      "MongoDB",
      "PayStack",
      "Unit Testing",
    ],
    repositoryUrl: "https://github.com/olatunde1998/geomatic-connect",
    projectUrl: "https://www.geomaticconnect.work/",
    category: ["TypeScript", "NextJs", "AI", "Web App", "PWA"],
    projectFeatures: [
      "🌐 Next.js App Router",
      "🔐 NextAuth Authentication",
      "📧 Email/Password Auth",
      "🔑 OAuth (Google and GitHub)",
      "💽 MongoDB Database",
      "💨 Payment Service with PayStack",
      "🎨 Styling with tailwindcss",
      "✅ Github Pull Request Template",
      "💵 Github Workflow",
      "🐐 Unit Testing",
      "😶‍🌫️ Deployment to Vercel",
      "💽 OutStanding ReadMe",
    ],
  },
  {
    id: "4",
    imageUrl: "/prepwise.png",
    projectTitle: "Prepwise AI",
    subTitle:
      "🚀  Prepwise: A job interview preparation platform powered by Vapi AI Voice agents. Leverages Vercel ai-sdk, Vapi voice agent, Prisma, MongoDB for database and utilized Tailwindcss for astonishing User Interfaces.",
    stack: [
      "TypeScript",
      "NextJS",
      "NextAuth",
      "React-Query",
      "Vercel ai-sdk",
      "Tailwindcss",
      "Prisma",
      "MongoDB",
      "Vapi AI",
      "Unit Testing",
    ],
    repositoryUrl: "https://github.com/olatunde1998/prepwise",
    projectUrl: "https://prepwise-azure.vercel.app/",
    category: ["TypeScript", "NextJs", "AI", "Web App"],
    projectFeatures: [
      "🌐 Next.js App Router",
      "🔐 NextAuth Authentication",
      "📧 Email/Password Auth",
      "💽 MongoDB Database",
      "🔐 Prisma ORM",
      "🎨 Styling with tailwindcss",
      "✅ Github Pull Request Template",
      "💵 Github Workflow",
      "🐐 Unit Testing",
      "😶‍🌫️ Deployment to Vercel",
      "💽 OutStanding ReadMe",
    ],
  },
  {
    id: "5",
    imageUrl: "/must.webp",
    projectTitle: "Must Culture Share: Internationalization with i18n",
    subTitle:
      "🚀 A multilingual must-culture website supporting five languages (English, Korean, Chinese, German, Arabic) built with Next.js, next-i18n, TailwindCSS, and Shadcn UI, with Sanity CMS for content management, deployed on Vercel",
    stack: [
      "TypeScript",
      "NextJS",
      "Kinde",
      "Sanity",
      "Vercel",
      "Tailwind",
      "Shadcn/UI",
      "Prisma",
    ],
    repositoryUrl: "https://github.com/olatunde1998/must",
    projectUrl: "https://must-geodevcodes.vercel.app/ko",
    category: ["TypeScript", "NextJs", "Web Application"],
    projectFeatures: [
      "🌐 Next.js App Router",
      "🎨 Styling with tailwindcss and shadcn UI",
      "✅ Github Pull Request Template",
      "💵 Github Workflow",
      "💵 Store Projects in Sanity",
      "🐐 Bento Layout",
      "💽 OutStanding ReadMe",
      "😶‍🌫️ Deployment to Vercel",
    ],
  },

  {
    id: "6",
    imageUrl: "/portfolio.png",
    projectTitle: "My Portfolio Website",
    subTitle: "🚀   AI Powered Portfolio with Blogify",
    stack: [
      "TypeScript",
      "NextJS",
      "NextAuth",
      "Vercel",
      "Tailwind",
      "Shadcn/UI",
      "MongoDB",
    ],
    repositoryUrl: "https://github.com/olatunde1998/geodevcodes-microfrontend",
    projectUrl: "https://geodevcodes.vercel.app/",
    category: ["TypeScript", "NextJs", "React-Redux", "AI", "Web App", "PWA"],
    projectFeatures: [
      "🌐 Next.js App Router",
      "🔐 Kinde Authentication",
      "📧 Passwordless Auth",
      "🔑 OAuth (Google and GitHub)",
      "🎨 Styling with tailwindcss and shadcn UI",
      "✅ Github Pull Request Template",
      "💵 Github Workflow",
      "💵 Store Projects in Sanity",
      "🐐 Bento Layout",
      "💽 OutStanding ReadMe",
      "😶‍🌫️ Deployment to Vercel",
    ],
  },
  {
    id: "7",
    imageUrl: "/real-estate.png",
    projectTitle: "RealEstate Mobile APP",
    subTitle:
      "🚀  Build a full-stack Real Estate application with React Native (Expo), featuring Google authentication, dynamic property listings, and user profiles. Designed with modern tools like Expo SDK 52, Tailwind CSS, and TypeScript for a seamless and scalable experience",
    stack: [
      "TypeScript",
      "ReactNative",
      "Expo",
      "Google Maps",
      "Expo EAS",
      "Tailwindcss",
    ],
    repositoryUrl: "https://github.com/olatunde1998/rn-realestate",
    projectUrl: "https://expo.dev/artifacts/eas/eTvG9HP2uxDtr7KsLrW42Q.apk",
    category: ["TypeScript", "ReactNative", "Expo", "ReactJs", "ReactNative"],
    projectFeatures: [
      "🌐 React Native (Expo)",
      "🔐 NestJs Backend",
      "🎨 Styling with tailwindcss",
      "✅ React TanStack Query",
      "🐐 React-Context API",
      "✅ Github Pull Request Template",
      "💵 Github Workflow",
      "😶‍🌫️ Deployment to Expo EAS",
      "💽 OutStanding ReadMe",
    ],
  },
  {
    id: "8",
    imageUrl: "/airide.png",
    projectTitle: "AIRIDE Mobile APP",
    subTitle:
      "🚀  Built with React Native for handling the user interface, Google Maps for rendering maps with directions, paystack for handling payments, and styled with TailwindCSS, AI Ride is a perfect mobile app",
    stack: [
      "TypeScript",
      "ReactNative",
      "Expo",
      "AI",
      "Google Maps",
      "Zustand",
      "AWS Amplify",
      "Tailwindcss",
    ],
    repositoryUrl: "https://github.com/olatunde1998/rn-aiRide",
    projectUrl: "https://expo.dev/artifacts/eas/vxr5E8gf1q25nq9HqYBF6u.apk",
    category: ["TypeScript", "ReactNative", "Expo", "ReactJs", "ReactNative"],
    projectFeatures: [
      "🌐 React Native (Expo)",
      "🔐 NestJs Backend",
      "🎨 Styling with tailwindcss",
      "✅ React TanStack Query",
      "🐐 React-Redux",
      "✅ Github Pull Request Template",
      "💵 Github Workflow",
      "😶‍🌫️ Deployment to Expo EAS",
      "💽 OutStanding ReadMe",
    ],
  },
  {
    id: "9",
    imageUrl: "/scoutbeta.png",
    projectTitle: "ScoutBeta: Marketplace for Space and Location Scouting",
    subTitle:
      "🚀 No.1 Online marketplace for space and location scouting for creators just in 3 clicks.",
    stack: [
      "TypeScript",
      "NextJS",
      "NextAuth",
      "Vercel",
      "Tailwind",
      "Shadcn/UI",
      "Zustand",
    ],
    repositoryUrl: "https://github.com/scoutbeta-solutions",
    projectUrl: "https://scoutbeta.vercel.app/",
    category: ["TypeScript", "NextJs", "Zustand", "Web App", "PWA"],
    projectFeatures: [
      "🌐 Next.js App Router",
      "🔐 NextAuth Authentication",
      "🔑 OAuth (Google and GitHub)",
      "💽 Supabase Database",
      "🎨 Styling with tailwindcss and shadcn UI",
      "✅ Github Pull Request Template",
      "💵 Github Workflow",
      "🐐 Bento Layout",
      "💽 OutStanding ReadMe",
      "😶‍🌫️ Deployment to AWS Amplify",
    ],
  },
  {
    id: "10",
    imageUrl: "/lms-2.png",
    projectTitle: "Learning Management System with Next.js.14, NextAuth",
    subTitle:
      "🚀 Create a modern Learning Management System For software developers  with Next.js.14, Tailwind,  Learn step-by-step and elevate your development skills.",
    stack: [
      "TypeScript",
      "NextJS",
      "NextAuth",
      "React-Query",
      "Vercel",
      "Tailwind",
      "Shadcn/UI",
      "Firebase",
      "PayStack",
      "Unit Testing",
    ],
    repositoryUrl: "https://github.com/olatunde1998/online-learning-app",
    projectUrl: "https://online-learning-application.vercel.app/",
    category: ["TypeScript", "NextJs", "Web App", "PWA", "ReactJs"],
    projectFeatures: [
      "🌐 Next.js App Router",
      "🔐 Firebase Authentication",
      "📧 Passwordless Auth",
      "🔑 OAuth (Google and GitHub)",
      "💨 Payment Service with PayStack",
      "🎨 Styling with tailwindcss and shadcn UI",
      "✅ Github Pull Request Template",
      "💵 Github Workflow",
      "🐐 Unit Testing",
      "😶‍🌫️ Deployment to Vercel",
      "💽 OutStanding ReadMe",
    ],
  },
  {
    id: "11",
    imageUrl: "/project-3.png",
    projectTitle:
      "NextJS 14 | Single Page application in getLinked-tech Hackathon 1.0",
    subTitle:
      "Welcome to the  NextJs GetLinked-Tech Hackathon. In this Application, we'll dive deep into the latest version of Remix.run, a cutting-edge framework for building full stack JavaScript applications.",
    stack: ["TypeScript", "NextJS", "Vercel", "Tailwind", "NodeJs"],
    repositoryUrl: "https://github.com/olatunde1998/getlinked-tech",
    projectUrl: "https://getlinked-tech.vercel.app/",
    category: ["Typescript", "NextJs", "Web Application", "ReactJs"],
    projectFeatures: [
      "🌐 Next.js App Router",
      "💽 NodeJs Database",
      "🎨 Styling with tailwindcss",
      "✅ Github Pull Request Template",
      "💵 Github Workflow",
      "🐐 React Hook Form",
      "😶‍🌫️ Deployment to Vercel",
      "💽 OutStanding ReadMe",
    ],
  },
  {
    id: "12",
    imageUrl: "/project-6.jpeg",
    projectTitle:
      "E-Commerce Website with Stripe, and Sanity.io | Full Stack Project",
    subTitle:
      "🚀 Full-Stack Ecommerce Website complete with secure Stripe payment integration, efficient content management through Sanity.io and beautiful styling using Tailwindcss and Shadcn UI for accessible components.",
    stack: [
      "TypeScript",
      "NextJS",
      "Kinde",
      "Sanity",
      "Vercel",
      "Tailwind",
      "Shadcn/UI",
      "Supabase",
    ],
    repositoryUrl: "https://github.com/olatunde1998/geodevcodes-ecommerce",
    projectUrl: "https://geodevcodes-ecommerce.vercel.app/",
    category: ["TypeScript", "NextJs", "Web App", "ReactJs"],
    projectFeatures: [
      "🌐 Next.js App Router",
      "🔐 Kinde Authentication",
      "📧 Passwordless Auth",
      "🔑 OAuth (Google and GitHub)",
      "💽 Supabase Database",
      "🎨 Styling with tailwindcss and shadcn UI",
      "✅ Github Pull Request Template",
      "💵 Github Workflow",
      "💵 Store Projects in Sanity",
      "💽 OutStanding ReadMe",
      "😶‍🌫️ Deployment to Vercel",
    ],
  },
  // {
  //   id: "12",
  //   imageUrl: "/project-4.png",
  //   projectTitle: "Modern Care-Finder App using Next.js 14, Firebase-Auth",
  //   subTitle:
  //     "🚀 Today we are going to create a Care-Finder App using Next.js 14, Firebase-Auth, Prisma, Firebase, and Tailwind! Learn step-by-step and elevate your development skills.",
  //   stack: ["TypeScript", "NextJS", "Vercel", "Tailwind", "Firebase", "Prisma"],
  //   repositoryUrl: "https://github.com/olatunde1998/carefinder-app",
  //   projectUrl: "https://carefinder-app.vercel.app/",
  //   category: ["TypeScript", "NextJs", "Web App", "ReactJs"],
  //   projectFeatures: [
  //     "🌐 Next.js App Router",
  //     "📧 Passwordless Auth",
  //     "🔑 OAuth (Google and GitHub)",
  //     "💽 Firebase Database",
  //     "💨 React TanStack Query",
  //     "🎨 Styling with tailwindcss",
  //     "✅ React TanStack Table",
  //     "💵 Store Projects in Firebase",
  //     "✅ Github Pull Request Template",
  //     "💵 Github Workflow",
  //     "😶‍🌫️ Deployment to Vercel & AWS Amplify",
  //     "💽 OutStanding ReadMe",
  //   ],
  // },
];

// Project Category Options
export const categoryOptions = [
  {
    label: "AI",
    value: "AI",
    icon: SiOpensourceinitiative,
  },
  {
    label: "NextJs",
    value: "NextJs",
    icon: SiNextdotjs,
  },
  {
    label: "PWA",
    value: "PWA",
    icon: SiPwa,
  },
  {
    label: "TypeScript",
    value: "TypeScript",
    icon: SiTypescript,
  },
  {
    label: "ReactJs",
    value: "ReactJs",
    icon: SiReact,
  },
];
